name: Extract Text from PDF

on:
  workflow_run:
    workflows: [Download Trader PDF]
    types:
      - completed
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./scripts
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run script
      working-directory: ./scripts
      run: |
        python extract_text_from_pdf.py
        
    - name: Commit created file
      run: |
        if test -f "data/registerTrader.csv"; then
            git config --global user.name "${GITHUB_ACTOR}"
            git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
            git add -A
            git commit -am "Update extacted csv  $(date +'%Y-%m-%dT%H:%M:%S') UTC"
            git push -f origin main
        fi
